- README.md
ReadMe changed, it has a lot of room for contribution! 😊
> Initial ReadMe Created

- index.html
Hi dude, hope you don't mind my humble changes...
> warning and hello

- index.html
> added spot for people to add their names

- README.md
- assets/css/style.css
- assets/js/functions.js
- contributors.md
- index.html
Replaced fluid-container class with container-fluid, 
fixed some plain text spelling in readme.md file including a file name,
added my name in the contributors file,
added my name in the contributors' list in the footer section
> fixed some issues with css and readme.md, added a timing function

- contributors.md
- index.html
Added some space to improve readability and some little comments.
> improve readability

- README.md
- assets/js/contributorsPanel.js
- contributors.md
This is my first ever pull request! It's easier than I thought it would be.
> edit README add name as contibutor

- index.html
- puzzels/puzzel1.html
Progressing the puzzel#1 prototype
> Integrate puzzel

- assets/css/style.css
- assets/js/functions.js
- index.html
A form added in index.html for google search,
Necessary CSS added for google search,
Necessary script added for google search.
> Added a Google Search Option

- puzzles/puzzle1.html
hey i like your new cell colors goes good with your profile pic 👍
> fixed link for development

- contributors.md
I added my name to the contributors.md text file
> added another name to contributors

- assets/css/style.css
- assets/js/contributorsPanel.js
I tried to fix the responsive design of the contributor panel, I await your opinions.
> fix responsive contributor panel

- assets/css/style.css
- index.html
The buttons taking up the whole screen was annoying me
> Make button container

- puzzles/puzzle1.html
Does anyone have a suggestion for naming this pull request?  Should I put my name in it?  Should I mention the file I changed?
> Added a camper cell

- assets/js/quizQuestions.js
There are now 10 total questions.
> Added one question to HTML

- assets/js/quizQuestions.js
i re added the javascript questions
> re added javascript questions

- Useful-links/Useful-links.html
- assets/css/Useful-links.css
- index.html
Add a section to share useful links. I await your opinions, I still need to polish it more.
> I added a section to share useful links

- assets/js/contributorsPanel.js
- contributors.md
Added my name to the contributors list
> Added Devansh to contributors list

- Useful-links/Useful-links.html
- assets/css/Useful-links.css
- assets/css/challenge1.css
Added some space in between camper cells and stopped the text squashing together when change page size by giving them a min-width. might look better like this?
> added camper cell space

- assets/css/challenge1.css
I changed the css for my campercell from challenge 1.  Just as practice for using the command line to commit.
> changed width of border

- assets/js/contributorsPanel.js
added myself (Terri Fricker) to the contributorPanel array
> add name to contributorPanel

- assets/js/quiz.js
At line 30 in quiz.js, I changed the first parameter in 'answer.replace' with a regular expression to catch all '<' and '>' tags.
> update quiz javascript

- assets/js/themes.js
- index.html
> create new theme - beach

- assets/js/themes.js
- index.html
This code is actually not working currently.  I've worked a few hours to find my bug.
> Spring Green Theme

- assets/js/themes.js
- index.html
@DavidMatthewFraser
Couple of the themes had missing button color so i added them in as what color i thought matched best feel free to change them if they dont, also i nearly forgot to add the theme to the switch statement, then i realised that it could be done quite easily without the switch statement so i thought it might be another good challenge for you to do?
> added dark theme

- assets/css/challenge2.css
My animation wasn't  working anymore.
> added a missing '{' to fix my comet animation

- README.md
This project further ... to  Further, this project ...
Grammar edit
> One sentence edit in README

- README.md
In the Add Useful Links section, it said to make changes to quiz.html.  I've changed it to Useful-links.html.
> changed a link

- README.md
> mistake in git command

- index.html
> Connect images

- home-page/style.css
- home-page/themes.js
- index.html
Done the main page responsiveness i think i got everything but probably forgot something lol as i always do,
i got rid of some bootstrap that was not needed or was just in the way stuff like adding a flex to a container instead of using spacers all over the place,
@DavidMatthewFraser this should be better?
> Responsiveness

- challenges/challenge-2/challenge-2.css
- challenges/challenge-2/challenge-2.html
On some screen sizes, I wasn't able to click the 'close' button on the challenge 2 instructions. I added a side scroller and decreased the height of the popup.
> now you can click off the instructions on any screen size

- Contributors.md
I would love to join and help.
> adding Brian Loveless to contributors markdown file

- Contributors.md
- home-page/contributors-panel.js
I would love to help contribute to this project. What an excellent Idea.
> Add brian to website

- Contributors.md
- challenges/challenge-1/challenge-1.css
- challenges/challenge-1/challenge-1.html
- home-page/contributors-panel.js
made a camper card for the site
> Challenge one brian loveless

- Contributors.md
Please consider me for addition to the repo! Thank you!
> Adding my name to the contributors.md file

- Contributors.md
- challenges/challenge-1/challenge-1.css
- challenges/challenge-1/challenge-1.html
- home-page/contributors-panel.js
Completed first challenge added my name to contribute list
> completed 1st challenge

- Contributors.md
- challenges/challenge-1/challenge-1.css
- challenges/challenge-1/challenge-1.html
Added name to contributors list and completed challenge 1.
> Jca branch

- quiz/quiz-questions.js
- quiz/quiz.js
Create a 4 question data structure quiz
> add data structure quiz

- index.html
Start Contributing button links to README in remote repository
> link to readme

- widgets/widgets.css
Made the widget home button match the buttons in the header of the homepage.
> Widget home button

- home-page/style.css
- widgets/widgets.css
I originally just commented out out the css that I moved to widget.css.  I finally removed it from index.css
> Home page css

- challenges/challenge-1/challenge-1.css
- challenges/challenge-1/challenge-1.html
- home-page/style.css
- home-page/themes.js
I also added the camper bot in challenge 1.
> Minor fixes and style changes.

- challenges/challenge-1/challenge-1.css
- challenges/challenge-1/challenge-1.html
> Challenge 1

- quiz/quiz.css
> changed max-width to 750 px

- waterTracker/index.html
- waterTracker/main.css
- waterTracker/main.js
Added water tracker project (html, css, and js - version).
> added water tracker project

- README.md
make it clear to contributors that they are cloning their fork
> More Clear

- README.md
There was some fake news in the instructions 😩
> Deleted Fake News

- widgets/waterTracker/main.js
Fixed bug. Bug - Does not show the alert on fresh start and goal is not showed.
> Fixed bug.

- challenges/challenge-1/challenge-1.html
Reverts DavidMatthewFraser/easy-to-git#225
> Revert "Update challenge-1.html"

- widgets/waterTracker/index.html
- widgets/waterTracker/main.css
- widgets/waterTracker/main.js
1> Added the animatate.css and animations in elements.
2> Restructured the index.html.
> Hacktoberfest

- home-page/themes.js
- index.html
Hi,
I add a new theme can you check my code and merge together?
Thank you
> Create sky theme changing CSS and add new dropdown-item in HTML

- home-page/contributors-panel.js
Hi,
I want to be a contributor to your project.
I add my name to contributors.js
let me know if the code has problems
Thank you :)
> I added my name in contributors' panel

- Contributors.md
- challenges/challenge-1/challenge-1.css
- challenges/challenge-1/challenge-1.html
Added a new div to challenge one and a new contributor.
> Added a new div to challenge one

- challenges/challenge-1/challenge-1.css
- challenges/challenge-1/challenge-1.html
Added my name to the contributor list and contributed to Challenge-1.
> Jenna's Changes

- Contributors.md
- challenges/challenge-1/challenge-1.css
- challenges/challenge-1/challenge-1.html
- home-page/contributors-panel.js
I completed challenge 1 and added myself as a contributor
> completed challenge1

- widgets/waterTracker/main.css
- widgets/waterTracker/main.js
added some settings on settingModal
> added some settings on settingModal

- Contributors.md
- challenges/challenge-1/challenge-1.css
- challenges/challenge-1/challenge-1.html
I added my name to the contributors.md file. 
Added a div, inserted my name, picture, and quote.
Stylized my contributor in CSS.
> add contributor crenauro

- challenges/challenge-1/challenge-1.css
- challenges/challenge-1/challenge-1.html
made the header a tiny bit smaller, and hopefully the files have now been formatted to prettier.
> small changes to font size in challenge 1 instructions

- challenges/challenge-1/challenge-1.html
- widgets/waterTracker/index.html
- widgets/waterTracker/main.css
- widgets/waterTracker/main.js
Added units setting in the setting modal
> Added units setting in the setting modal

- Contributors.md
- challenges/challenge-1/challenge-1.css
- challenges/challenge-1/challenge-1.html
- Added name to contributors' list.
- Added new profile card with custom styling.
> JC Hacktoberfest2020

- challenges/challenge-1/challenge-1.css
- challenges/challenge-1/challenge-1.html
> challenge 1 quote cell

- quiz/quiz-questions.js
- quiz/quiz.js
> added a new quiz section Sql #176

- useful-links/useful-links.html
> Removed the unnecessary li elements.

- Contributors.md
- challenges/challenge-1/challenge-1.css
- challenges/challenge-1/challenge-1.html
- Created my cell in the cell panel.
- Added my details to contributors.md
in response to #192 #195
> Challenge 1 - Hacktoberfest

- quiz/quiz-questions.js
Added two HTML quiz questions and then removed the extra comma on line 143!
> Quiz questions

- Contributors.md
- home-page/contributors-panel.js
> added mViolet to contributors list/panel

- global/js/themes.js
- home-page/themePicker.js
- index.html
> Theme Change

- challenges/challenge-1/challenge-1.css
- challenges/challenge-1/challenge-1.html
- home-page/contributors-panel.js
Challenge Files and contribution panel
> Challenge Files

- CONTRIBUTING.md
- Contributors.md
Fixed wrong path for "Add a feature" section
* Reproduce Bug*
1. master > Contributing.md > line 35
2. see yourself
* Changes*
1. Fixed the path
> Fixed Contributing.md Add feature section

- challenges/challenge-1/challenge-1.css
There was a stray '#' that was outside of a comment that was causing an error.
> remove a stray '#'

- challenges/challenge-2/challenge-2.css
- challenges/challenge-2/challenge-2.html
Also just learned that not all of images that have the background transparent are actually transparent ahah
> Added a blue sun in challenge 2 :D
